import { Provider, VerificationRecord, AuditLogEntry, PendingReview } from "@/types";

export const mockProviders: Provider[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    organization: "Johnson Educational Services",
    serviceType: "evaluator",
    location: "Los Angeles, CA",
    zip: "90001",
    cost: "$150-$300/session",
    lastVerified: "2026-02-15",
    nextVerificationDue: "2026-08-15",
    status: "verified",
    phone: "(555) 123-4567",
    email: "sarah@example.com",
    website: "https://example.com",
    languages: ["English", "Spanish"],
    notes: "Specializes in learning disabilities",
    populationsServed: ["K-12", "Adults"],
    insurance: ["Blue Cross", "Aetna", "Private Pay"],
    licenseNumber: "PSY-12345",
    specializations: ["ADHD", "Dyslexia", "Learning Disabilities"],
    verifiedBy: "Staff Admin",
    verificationNotes: "All credentials verified. Website active.",
    visibleToLLM: true,
    createdDate: "2025-08-01",
    modifiedDate: "2026-02-15",
    views: 156,
    referrals: 42,
  },
  {
    id: "2",
    name: "Maria Rodriguez",
    serviceType: "tutor",
    location: "San Diego, CA",
    zip: "92101",
    cost: "Sliding scale ($25-$75)",
    lastVerified: "2026-01-10",
    nextVerificationDue: "2026-07-10",
    status: "pending",
    phone: "(555) 234-5678",
    email: "maria@example.com",
    languages: ["English", "Spanish"],
    populationsServed: ["K-8"],
    insurance: ["Private Pay"],
    specializations: ["Math", "Reading"],
    visibleToLLM: false,
    createdDate: "2026-01-10",
    modifiedDate: "2026-01-10",
    views: 23,
    referrals: 5,
  },
  {
    id: "3",
    name: "Community Advocacy Center",
    organization: "Community Advocacy Center",
    serviceType: "advocate",
    location: "Oakland, CA",
    zip: "94601",
    cost: "Free",
    lastVerified: "2025-11-20",
    nextVerificationDue: "2026-05-20",
    status: "needs-update",
    phone: "(555) 345-6789",
    email: "info@cacenter.org",
    website: "https://cacenter.org",
    languages: ["English", "Mandarin", "Cantonese"],
    notes: "Serves families in Alameda County",
    populationsServed: ["All ages"],
    insurance: ["Free services"],
    specializations: ["IEP advocacy", "Due process"],
    verifiedBy: "John Doe",
    verificationNotes: "Due for re-verification",
    visibleToLLM: true,
    createdDate: "2025-03-15",
    modifiedDate: "2025-11-20",
    views: 298,
    referrals: 87,
  },
  {
    id: "4",
    name: "Dr. Michael Chen",
    serviceType: "therapist",
    location: "San Francisco, CA",
    zip: "94102",
    cost: "$120/hour",
    lastVerified: "2026-02-18",
    nextVerificationDue: "2026-08-18",
    status: "verified",
    phone: "(555) 456-7890",
    email: "mchen@example.com",
    languages: ["English", "Mandarin"],
    populationsServed: ["Children", "Adolescents"],
    insurance: ["Kaiser", "Cigna", "Private Pay"],
    licenseNumber: "LMFT-67890",
    specializations: ["Anxiety", "Depression", "Family therapy"],
    verifiedBy: "Staff Admin",
    verificationNotes: "License verified with state board",
    visibleToLLM: true,
    createdDate: "2025-06-10",
    modifiedDate: "2026-02-18",
    views: 189,
    referrals: 54,
  },
];

export const mockVerificationHistory: Record<string, VerificationRecord[]> = {
  "1": [
    {
      id: "v1",
      providerId: "1",
      date: "2026-02-15",
      staffMember: "Staff Admin",
      action: "Verified provider information",
      notes: "All credentials verified. Website active.",
    },
    {
      id: "v2",
      providerId: "1",
      date: "2025-08-10",
      staffMember: "Jane Smith",
      action: "Initial verification",
      notes: "Initial onboarding complete",
    },
  ],
  "2": [
    {
      id: "v3",
      providerId: "2",
      date: "2026-01-10",
      staffMember: "Staff Admin",
      action: "Added to directory",
      notes: "Pending verification",
    },
  ],
  "3": [
    {
      id: "v4",
      providerId: "3",
      date: "2025-11-20",
      staffMember: "John Doe",
      action: "Verified provider information",
      notes: "6-month verification completed",
    },
    {
      id: "v5",
      providerId: "3",
      date: "2025-03-15",
      staffMember: "Jane Smith",
      action: "Initial verification",
    },
  ],
  "4": [
    {
      id: "v6",
      providerId: "4",
      date: "2026-02-18",
      staffMember: "Staff Admin",
      action: "Verified provider information",
      notes: "License verified with state board",
    },
  ],
};

export const mockAuditLog: AuditLogEntry[] = [
  {
    id: "a1",
    providerId: "1",
    providerName: "Dr. Sarah Johnson",
    staffMember: "Staff Admin",
    action: "verified",
    timestamp: "2026-02-15T10:30:00",
    notes: "All credentials verified",
  },
  {
    id: "a2",
    providerId: "2",
    providerName: "Maria Rodriguez",
    staffMember: "Staff Admin",
    action: "created",
    timestamp: "2026-01-10T14:20:00",
    notes: "New provider added",
  },
  {
    id: "a3",
    providerId: "3",
    providerName: "Community Advocacy Center",
    staffMember: "John Doe",
    action: "verified",
    timestamp: "2025-11-20T09:15:00",
  },
  {
    id: "a4",
    providerId: "4",
    providerName: "Dr. Michael Chen",
    staffMember: "Staff Admin",
    action: "verified",
    timestamp: "2026-02-18T16:45:00",
    notes: "License verified with state board",
  },
  {
    id: "a5",
    providerId: "1",
    providerName: "Dr. Sarah Johnson",
    staffMember: "Jane Smith",
    action: "edited",
    timestamp: "2025-12-05T11:30:00",
    changes: "Updated phone number",
  },
];

export const mockPendingReviews: PendingReview[] = [
  {
    id: "pr1",
    providerId: "2",
    provider: mockProviders[1],
    submittedDate: "2026-02-18",
    priority: "high",
    reason: "New provider - needs initial verification",
  },
  {
    id: "pr2",
    providerId: "5",
    provider: {
      id: "5",
      name: "ABC Therapy Services",
      serviceType: "therapist",
      location: "Sacramento, CA",
      zip: "95814",
      cost: "$100-$150/session",
      lastVerified: "2026-02-10",
      nextVerificationDue: "2026-08-10",
      status: "pending",
      phone: "(555) 567-8901",
      email: "info@abctherapy.com",
      website: "https://abctherapy.com",
      languages: ["English"],
      populationsServed: ["All ages"],
      insurance: ["Most major insurance"],
      visibleToLLM: false,
      createdDate: "2026-02-10",
      modifiedDate: "2026-02-17",
    },
    previousVersion: {
      cost: "$90-$140/session",
      phone: "(555) 567-8900",
    },
    submittedDate: "2026-02-17",
    priority: "medium",
    reason: "Information updated - needs re-verification",
    changedFields: ["cost", "phone"],
  },
];